spring:
  mail:
    host: smtp.qq.com
    username: ENC(XDBbgMG83fE/4TMzP3GDYcX9ixWDoEgYXGqpuyNDYeVb8t5CmKJWzc5XR8VQDnSk)
    password: ENC(lnPGSxpiXbL7q26ORR8M7qzfh3jqNZlUDle5IbTVyUhux67Us4eu5f6xXptSjFIv)
    port: 465
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          auth: true
          starttls:
            enable: true
            required: true

#jasypt:
#  encryptor:
#    password: test